{% set name = "ldas-tools-diskcacheAPI" %}
{% set version = "2.7.1" %}
{% set sha256 = "23ad6778367d628958e3219de8a9c7672ee327d67dd78186a9b9d2abc8667f49" %}

# dependencies
{% set ldas_tools_cmake_version = "1.2.2" %}
{% set ldas_tools_al_version = "2.6.5" %}
{% set ldas_tools_ldasgen_version = "2.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - osx-initd.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("ldas-tools-diskcacheapi", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - pkg-config  # [unix]
  host:
    - boost-cpp
    - ldas-tools-al {{ ldas_tools_al_version }}
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
    - ldas-tools-ldasgen {{ ldas_tools_ldasgen_version }}
  run:
    - ldas-tools-al >={{ ldas_tools_al_version }}
    - ldas-tools-ldasgen >={{ ldas_tools_ldasgen_version }}

test:
  requires:
    - pkg-config  # [unix]
  commands:
    - diskcache --help
    - pkg-config --print-errors --modversion ldastools-diskcache  # [unix]

about:
  home: https://wiki.ligo.org/Computing/LDASTools
  dev_url: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LDAS tools diskcacheAPI library
  description: |
    LDAS tools diskcacheAPI library. This package provides the runtime
    libraries and executables but does not provide the systemd
    infrastructure to run diskcache as a service.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
