{% set name = "ldas-tools-diskcacheAPI" %}
{% set version = "2.7.0" %}
{% set sha256 = "8b86017a30a1d282cc7e241a07c82e7b33b075b487efa74659be6d718940c432" %}

{% set ldas_tools_al_version = "2.6.2" %}
{% set ldas_tools_ldasgen_version = "2.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config  # [not win]
    - make  # [not win]
  host:
    - boost-cpp
    - ldas-tools-al >={{ ldas_tools_al_version }}
    - ldas-tools-ldasgen >={{ ldas_tools_ldasgen_version }}
  run:
    - ldas-tools-al >={{ ldas_tools_al_version }}
    - ldas-tools-ldasgen >={{ ldas_tools_ldasgen_version }}

test:
  commands:
    # check executables
    - diskcache --help
    # check libraries
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://wiki.ligo.org/Computing/DASWG/LDASTools
  doc_url: https://ldastools.docs.ligo.org/LDAS_Tools/Beta/doc/ldas-tools-diskcacheAPI/diskcache/html/
  dev_url: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPLv2
  license_family: GPL
  license_file: COPYING
  summary: LDAS tools diskcacheAPI library
  description: |
    LDAS tools diskcacheAPI library. This package provides the runtime
    libraries and executables but does not provide the systemd
    infrastructure to run diskcache as a service.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
