travis:
  secure:
    BINSTAR_TOKEN: fbVXVwZ0UOvGLTOKlg9sIhrOA1vr7DeQg/+BcTIC6GDdR+Q3n9FeweuCW2r+HnzY2q0RJMb3YWqnZzMYtCFhlBoYMQN+ddKKIAttH4XqU1SkoB0dKCwu4q5Lkf2FKQTE2gfO+v1d0w9nQrdzrm1//ezZwVQLgBVxE9q6Y+RpjMj9tVO63JCalODaVTrBkTZ54NcmkTKDDLdhAT+c8KVdpErjuQv/RP4CFGFNYBc8GRBZzXyxDTDgQTP/rtBYS/xDSVwMehqzA0gckTMDBdHmXdOVGL3PCW/lkgQfZMGGFkkz1pXyKFdW7drTldNrfj7hM6OkmwaqHVP3dZRMwzBLKRbRLSdbHum0Nudc6myI9/iZ9DTy21BufMHusY1FyiubuI57EMZ4NZfC6+g1gwVcjHfGuCrFmNgMBa9MVDxuzplESWvE3Nyy2SWDX0q4zjNGWo0KXh6capq10sJFPV7ZgTORHufNvGKH6PnyENr9vnmT6AWFvHlsRA9vkExmVrH2aspu/YSJaMIivAE+PrW6ed1ZvS3aPQWkTFxAL3pX+nx+K3xlom9TvVr4w+BHnas5cumOPnexhS6EjtPjUerz7MPAcl5Ehdnkv4sG7GeC1G8KW6/ZJ5piSZstV7O3iHZkhgc/u/5I/+QSsede6HuM+G3HhgzkkSm2iK0ZnYlupnU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
